print("Hello World!")
print("Hello again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print('Make your script print another line.')
print("Another line for fun.")
